### ISSUE TITLE
Background download support ?

### ISSUE THREAD

**Issue by levinIleaf** [cornerAnt/Digger#10]
Can you make digger to support background download?

**Comment by cornerAnt** [comment]
If you want to support background downloads, use the URLSessionDownloadTask.
I'm using the URLSessionDataTask.

**Comment by Rashesh-Bosamiya** [comment]
However, If we use `URLSessionDownloadTask` need to handle its `delegate` methods.


I have attempted to write delegate methods, but having bit of difficulty in callbacks.

Can you rewrite `Delegate` methods for `URLSessionDownloadTask`?

I am facing following issue.

_https://stackoverflow.com/questions/29909351/accessing-the-bytes-from-nsurlsessiondownloadtask-as-they-are-downloaded_

**Thanks.**

**Comment by Raghav13RV** [comment]
Any updates on This???
Can u add background downloading Support ?
