### ISSUE TITLE
作者你好，看到你的库我很激动

### ISSUE THREAD

**Issue by Danie1s** [cornerAnt/Digger#2]
之前我也花了一些时间写了一个很你这个库很像的下载器，里面的类名，方法名称，链式调用的特点，都很像，可能这就是缘分吧。本人水平有限，你写得应该会比我好，所以打算使用你的库，但是好像有不满足我的需求。
我需要传入一个urlString数组，然后开启下载，下载的过程中我要得到这组任务的总进度，并且这组任务全部下载完，我在拿到回调做事情处理，也就是一个multiDownload的方法。如果你有兴趣的话，请加入这个功能，或者加我的QQ：176516837，一起讨论

**Comment by cornerAnt** [comment]
@Danie1s  下个版本会考虑加上吧,QQ就不用了吧,这里讨论就行
