### ISSUE TITLE
是否需要针对类似403这类HTTP状态码做处理？

### ISSUE THREAD

**Issue by numbbuaa** [cornerAnt/Digger#3]
您好，看代码实现，好像没有针对403之类的http状态码进行处理？

**Comment by cornerAnt** [comment]
不知道你的意思是啥.所有的失败信息都在失败的回调里了

**Comment by numbbuaa** [comment]
@cornerAnt  有个问题，一些下载链接有可能会有时效性，过了有效期之后会再请求会返回403，这个时候

```
- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task
didCompleteWithError:(nullable NSError *)error

```
回调方法里面error是nil，按照你的实现，这种情况会走成功的回调

这里给一个测试url: http://v3-tt.ixigua.com/4b02b9f95861aac9b03775c6ba3ebcd2/5a0067a2/video/m/220be69b3d527bf413d82886b27634ddba81151ff3b0000691b80e4b57f/

**Comment by cornerAnt** [comment]
这个重定向的问题   你这个URL本身就不合法  不是真实的

**Comment by cornerAnt** [comment]
@numbbuaa  你这个URL重定向问题,URL本身就不是合法的地址...

**Comment by numbbuaa** [comment]
@cornerAnt   这个和重定向没有关系吧 只是刚好我给的这个URL会重定向而已 你随便找个网易云音乐歌曲下载地址也行 过了一段时间 再访问也是403 按说库应该针对这种情况做处理的吧 再就是传入的URL（比如开发时候传入路径少拼了一段之类的）如果返回是404（回调的error也是nil）这种 也应该有处理

**Comment by cornerAnt** [comment]
@numbbuaa  我明白你的意思了,第一你下载的地址不是真实的地址,真实的地址应该是.....mp4之类的,你可以搜下解析网易云音乐真实的地址,  第二,你说的判断状态码可以 我会加入200到400的 验证   很感谢

**Comment by numbbuaa** [comment]
@cornerAnt  我提供的测试URL的确是真实的曾经可用的资源的URL，这一点是可以肯定的，至于你说的真实的URL必须是带mp4文件后缀的 这个不一定需要吧（资源类型和它的资源文件名称没有必然的关系，一个图片我也可以把它命名为mp3文件后缀的，只要把它当做图片文件读取也没有问题） 这里再给你一个不会重定向的URL进行测试 http://v1-tt.ixigua.com/2ff8b9609fb0b6c4587e8cd0cdd07892/5a006650/video/m/2201bc2d7f86dc448108dbc20441a9e48551151d86400006f28ada83ca5/

**Comment by cornerAnt** [comment]
@numbbuaa  请你认清楚什么叫做真实的地址 谢谢 还有不用回复了
