### ISSUE TITLE
Checking for file existence 

### ISSUE THREAD

**Issue by shevy555** [cornerAnt/Digger#4]
I recommend adding a validation for file existence since I always getting an error about file existence

**Comment by cornerAnt** [comment]
public enum DiggerError: Int {
    
    case badURL = 9981
    case fileIsExist = 9982
    case fileInfoError = 9983
    case invalidStatusCode = 9984
    case diskOutOfSpace = 9985
    case downloadCanceled = -999
    
}

When the file exists, the download task will not be started.
