### ISSUE TITLE
iOS8崩溃

### ISSUE THREAD

**Issue by seahuai** [cornerAnt/Digger#6]
dyld: Symbol not found: _NSURLSessionTaskPriorityDefault
Referenced from: /private/var/mobile/Containers/Bundle/Application/*******
Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
in /private/var/mobile/Containers/Bundle/Application/**********
(lldb)

需要在Digger的Target中添加`CFNetwork`

**Comment by cornerAnt** [comment]
感谢你的建议 @seahuai  我将会在下个版本加上
