### ISSUE TITLE
stopAllTasks() not working

### ISSUE THREAD

**Issue by alexandrutomescu** [cornerAnt/Digger#8]
In the example project, I press the top `Stop` button, but the downloads keep running. 

I also commented 
`NotificationCenter.default.post(name:NSNotification.Name(rawValue: suspendNotificationName), object: ExampleCell.self)
`
but they still keep running. So it might be something in Digger, not in the example project.

I'm running iOS 11 Simulator.

**Comment by cornerAnt** [comment]
Thank you for your issue,you are right.I judged that the download task was wrong.


                if diggerSeed.downloadTask.state == .running{
                    diggerSeed.downloadTask.suspend()
                    diggerDelegate?.notifySpeedZeroCallback(diggerSeed)
                }


I'll fix it in the next version
@alexandrutomescu
